name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ['hyperenv', 'medium']
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'actions/setup-node@v4'
      with:
        node-version: '20'
    - run: |
        npm ci
        npm test
